# Define a function to create a Vivado project structure
function create_pl_project {
    local pl=$1  # The project name
    
    # Create directories for the Vivado project
    mkdir $pl/vivado_project
    mkdir $pl/srcs
    mkdir $pl/srcs/constrs
    mkdir $pl/srcs/bd
    mkdir $pl/srcs/ip
    mkdir $pl/srcs/sim

    # Create and initialize the build script
    touch $pl/build_project.tcl
    echo "# overwrite this file using 'File > Project > Write Tcl' everytime after development" >> $pl/build_project.tcl

    # Create and initialize the .gitignore file
    touch $pl/.gitignore
    # Add entries to the .gitignore file
    echo "# files/folders generated by launching vivado" >> $pl/.gitignore
    echo ".Xil" >> $pl/.gitignore
    echo "*.jou" >> $pl/.gitignore
    echo "*.log" >> $pl/.gitignore
    echo "*.str" >> $pl/.gitignore
    echo "*.zip" >> $pl/.gitignore
    echo "" >> $pl/.gitignore
    echo "# default name for vivado project location" >> $pl/.gitignore
    echo "vivado_project" >> $pl/.gitignore
    echo "# custom name for vivado project location with sufix _project" >> $pl/.gitignore
    echo "*_project" >> $pl/.gitignore
    echo "" >> $pl/.gitignore
    echo "# keep only vivado managed bd hdl wrapper" >> $pl/.gitignore
    echo "srcs/bd/*.*" >> $pl/.gitignore
    echo "srcs/bd/*/*" >> $pl/.gitignore
    echo "!srcs/bd/*/hdl" >> $pl/.gitignore
    echo "srcs/bd/*/hdl/*" >> $pl/.gitignore
    echo "!srcs/bd/*/hdl/*_wrapper.v" >> $pl/.gitignore
    echo "" >> $pl/.gitignore
    echo "# keep only .xci file of ip" >> $pl/.gitignore
    echo "srcs/ip/*.*" >> $pl/.gitignore
    echo "srcs/ip/*/*" >> $pl/.gitignore
    echo "!srcs/ip/*/*.xci" >> $pl/.gitignore
}