# Define a function to create an SDK project structure
function create_ps_project {
    local ps=$1  # The project name

    # Create and initialize the build script
    touch $ps/build_workspace.tcl
    echo "# set workspace" >> $ps/build_workspace.tcl
    echo "sdk setws ." >> $ps/build_workspace.tcl
    echo "# import projects" >> $ps/build_workspace.tcl
    echo "sdk importprojects ." >> $ps/build_workspace.tcl
    echo "# launch sdk" >> $ps/build_workspace.tcl
    echo "exec xsdk -workspace ." >> $ps/build_workspace.tcl

    # Create and initialize the .gitignore file
    touch $ps/.gitignore
    # Add entries to the .gitignore file
    echo "# files/folders generated by launching sdk" >> $ps/.gitignore
    echo ".Xil" >> $ps/.gitignore
    echo "*.log" >> $ps/.gitignore
    echo ".metadata" >> $ps/.gitignore
    echo ".sdk" >> $ps/.gitignore
    echo "RemoteSystemsTempFiles" >> $ps/.gitignore
    echo "webtalk" >> $ps/.gitignore
    echo "" >> $ps/.gitignore
    echo "# keep only system.hdf and .project in hw projects" >> $ps/.gitignore
    echo "*_hw_platform_*/*" >> $ps/.gitignore
    echo "!*_hw_platform_*/.project" >> $ps/.gitignore
    echo "!*_hw_platform_*/*.hdf" >> $ps/.gitignore
    echo "" >> $ps/.gitignore
    echo "# keep only .mss, .project, .cproject, .sdkproject, and Makefile in bsp projects" >> $ps/.gitignore
    echo "*_bsp/*" >> $ps/.gitignore
    echo "!*_bsp/*.mss" >> $ps/.gitignore
    echo "!*_bsp/Makefile" >> $ps/.gitignore
    echo "!*_bsp/.project" >> $ps/.gitignore
    echo "!*_bsp/.cproject" >> $ps/.gitignore
    echo "!*_bsp/.sdkproject" >> $ps/.gitignore
    echo "" >> $ps/.gitignore
    echo "# keep only src, .project, .cproject in app projects" >> $ps/.gitignore
    echo "Debug" >> $ps/.gitignore
    echo "/*/src/README.txt" >> $ps/.gitignore
    echo "/*/src/Xilinx.spec" >> $ps/.gitignore
}