# Define a function to create a Vivado project structure
function create_pl_project {
    local pl=$1  # The project name
    
    # Create directories for the Vivado project
    mkdir $pl/vivado_project
    mkdir $pl/srcs
    mkdir $pl/srcs/constrs
    mkdir $pl/srcs/bd
    mkdir $pl/srcs/ip
    mkdir $pl/srcs/sim

    # Create and initialize the build script
    touch $pl/build_project.tcl
    echo "# overwrite this file using 'File > Project > Write Tcl' everytime after development" >> $pl/build_project.tcl

    # Create and initialize the .gitignore file
    touch $pl/.gitignore

cat <<EOT >> $pl/.gitignore
# files/folders generated by launching vivado
.Xil
*.jou
*.log
*.str
*.zip

# default name for vivado project location
vivado_project
# custom name for vivado project location with sufix _project
*_project

# keep only vivado managed bd hdl wrapper
srcs/bd/*.*
srcs/bd/*/*
!srcs/bd/*/hdl
srcs/bd/*/hdl/*
!srcs/bd/*/hdl/*_wrapper.v

# keep only .xci file of ip
srcs/ip/*.*
srcs/ip/*/*
!srcs/ip/*/*.xci
EOT

}